apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.volume.claimName" . | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
