apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    app: {{include "postgres.fullname" . | quote }}
    deploymentconfig: {{ include "postgres.fullname" . | quote }}
