apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    group: {{ .Values.postgres.group }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    app: {{include "postgres.fullname" . | quote }}
    deploymentconfig: {{ include "postgres.fullname" . | quote }}
