apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . | quote }}
  labels:
    {{- include "postgres.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service.port }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{ include "postgres.fullname" . | quote }}
    deploymentconfig: {{ include "postgres.fullname" . | quote }}
