# Default values for postgres.

# Override the base name of the created object
nameOverride: ""
# Override the full name of the created object
fullnameOverride: ""
# Override the namespace that the chart is deployed into
namespaceOverride: ""

postgres:
  name: postgres
  group: db
  container:
    image: postgres:9.6-alpine
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    pvc:
      name: postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi
  config:
    name: postgres-config
    data:
      - key: POSTGRES_USER
        value: postgres # init-db script will create the default database and user from this value - optional
      - key: POSTGRES_PASSWORD
        value: postgres # Value must be set, sets the default password for the superuser
    # - POSTGRES_DB: optional environment variable can be used to define a different name for the default database

# Override the repository and tag
image:
  registry: docker.io
  repository: postgres
  pullPolicy: IfNotPresent
  tag: 15.3-bullsye
  debug: false

service:
  enabled: true
  type: ClusterIP
  port:
    protocol: TCP
    port: 5432
    name:
    targetPort:
  additionalPorts: []
    # - name: "8080-udp"
    #   port: 8080
    #   protocol: UDP

ingres:
  enabled: false
  annotations: {}
  labels: {}

replicaCount: 1

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /var/lib/postgresql/data
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false

strategy:
  type: RollingUpdate


# Environment Variables
secrets: {}

secretsFrom: {}

env:
  POSTGRES_USER: postgres # init-db script will create the default database and user from this value - optional
  POSTGRES_PASSWORD: postgres # Value must be set, sets the default password for the superuser
  # - POSTGRES_DB: optional environment variable can be used to define a different name for the default database

envFrom: {}

postgresMaxConnections: 100

# Databases to create during initialisation
databases: []
# Users to create during initialisation
users: []

initSql: []

dnsPolicy: ClusterFirst

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 5
    timeoutSeconds: 10
  readiness:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 5
    timeoutSeconds: 10
  startup:
    enabled: false
    initialDelaySeconds: 5
    failureThreshold: 30
    periodSeconds: 10

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
